# **1. IMPORT LIBRARY**

In [1]:
import pandas as pd
import numpy as np
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer
from nltk.stem import WordNetLemmatizer
from nltk.corpus import wordnet
nltk.download('punkt_tab')
nltk.download('stopwords')
nltk.download('wordnet')
import re
import string

[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\Thinkpad\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Thinkpad\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\Thinkpad\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

# **2. DATA LOADING**

In [2]:
print("DATA GAMES")
df_games = pd.read_csv("../data/raw/games.csv")
display(df_games.head())
print("\nInfo Data Games: ")
df_games.info()

DATA GAMES

,app_id,title,date_release,win,mac,linux,rating,positive_ratio,user_reviews,price_final,price_original,discount,steam_deck
0,13500,Prince of Persia: Warrior Within™,2008-11-21,True,False,False,Very Positive,84,2199,9.99,9.99,0.0,True
1,22364,BRINK: Agents of Change,2011-08-03,True,False,False,Positive,85,21,2.99,2.99,0.0,True
2,113020,Monaco: What's Yours Is Mine,2013-04-24,True,True,True,Very Positive,92,3722,14.99,14.99,0.0,True
3,226560,Escape Dead Island,2014-11-18,True,False,False,Mixed,61,873,14.99,14.99,0.0,True
4,249050,Dungeon of the ENDLESS™,2014-10-27,True,True,False,Very Positive,88,8784,11.99,11.99,0.0,True

Info Data Games:
<class 'pandas.DataFrame'>
RangeIndex: 50872 entries, 0 to 50871
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   app_id          50872 non-null  int64
 1   title           50872 non-null  str
 2   date_release    50872 non-null  str
 3   win             50872 non-null  bool
 4   mac             50872 non-null  bool
 5   linux           50872 non-null  bool
 6   rating          50872 non-null  str
 7   positive_ratio  50872 non-null  int64
 8   user_reviews    50872 non-null  int64
 9   price_final     50872 non-null  float64
 10  price_original  50872 non-null  float64
 11  discount        50872 non-null  float64
 12  steam_deck      50872 non-null  bool
dtypes: bool(4), float64(3), int64(3), str(3)
memory usage: 3.7 MB

In [3]:
print("DATA REKOMENDASI")
df_recom = pd.read_csv("../data/raw/recommendations.csv")
display(df_recom.head())
print("\nInfo Data Rekomendasi: ")
df_recom.info()

DATA REKOMENDASI

,app_id,helpful,funny,date,is_recommended,hours,user_id,review_id
0,975370,0,0,2022-12-12,True,36.3,51580,0
1,304390,4,0,2017-02-17,False,11.5,2586,1
2,1085660,2,0,2019-11-17,True,336.5,253880,2
3,703080,0,0,2022-09-23,True,27.4,259432,3
4,526870,0,0,2021-01-10,True,7.9,23869,4

Info Data Rekomendasi:
<class 'pandas.DataFrame'>
RangeIndex: 41154794 entries, 0 to 41154793
Data columns (total 8 columns):
 #   Column          Dtype
---  ------          -----
 0   app_id          int64
 1   helpful         int64
 2   funny           int64
 3   date            str
 4   is_recommended  bool
 5   hours           float64
 6   user_id         int64
 7   review_id       int64
dtypes: bool(1), float64(1), int64(5), str(1)
memory usage: 2.2 GB

In [4]:
print("DATA METADATA")
df_meta = pd.read_json('../data/raw/games_metadata.json', lines=True)

display(df_meta.head())
print("\nInfo Data Metadata:")
df_meta.info()

DATA METADATA

,app_id,description,tags
0,13500,Enter the dark underworld of Prince of Persia ...,"[Action, Adventure, Parkour, Third Person, Gre..."
1,22364,,[Action]
2,113020,Monaco: What's Yours Is Mine is a single playe...,"[Co-op, Stealth, Indie, Heist, Local Co-Op, St..."
3,226560,Escape Dead Island is a Survival-Mystery adven...,"[Zombies, Adventure, Survival, Action, Third P..."
4,249050,Dungeon of the Endless is a Rogue-Like Dungeon...,"[Roguelike, Strategy, Tower Defense, Pixel Gra..."

Info Data Metadata:
<class 'pandas.DataFrame'>
RangeIndex: 50872 entries, 0 to 50871
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   app_id       50872 non-null  int64
 1   description  50872 non-null  str
 2   tags         50872 non-null  object
dtypes: int64(1), object(1), str(1)
memory usage: 1.2+ MB

# **3.  DATA MERGING**

In [5]:
# Menggabungkan data games dan metadata berdasarkan app_id
df_games_meta = pd.merge(df_games, df_meta, on='app_id', how='inner')
display(df_games_meta.head())
df_games_meta.info()

,app_id,title,date_release,win,mac,linux,rating,positive_ratio,user_reviews,price_final,price_original,discount,steam_deck,description,tags
0,13500,Prince of Persia: Warrior Within™,2008-11-21,True,False,False,Very Positive,84,2199,9.99,9.99,0.0,True,Enter the dark underworld of Prince of Persia ...,"[Action, Adventure, Parkour, Third Person, Gre..."
1,22364,BRINK: Agents of Change,2011-08-03,True,False,False,Positive,85,21,2.99,2.99,0.0,True,,[Action]
2,113020,Monaco: What's Yours Is Mine,2013-04-24,True,True,True,Very Positive,92,3722,14.99,14.99,0.0,True,Monaco: What's Yours Is Mine is a single playe...,"[Co-op, Stealth, Indie, Heist, Local Co-Op, St..."
3,226560,Escape Dead Island,2014-11-18,True,False,False,Mixed,61,873,14.99,14.99,0.0,True,Escape Dead Island is a Survival-Mystery adven...,"[Zombies, Adventure, Survival, Action, Third P..."
4,249050,Dungeon of the ENDLESS™,2014-10-27,True,True,False,Very Positive,88,8784,11.99,11.99,0.0,True,Dungeon of the Endless is a Rogue-Like Dungeon...,"[Roguelike, Strategy, Tower Defense, Pixel Gra..."

<class 'pandas.DataFrame'>
RangeIndex: 50872 entries, 0 to 50871
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   app_id          50872 non-null  int64
 1   title           50872 non-null  str
 2   date_release    50872 non-null  str
 3   win             50872 non-null  bool
 4   mac             50872 non-null  bool
 5   linux           50872 non-null  bool
 6   rating          50872 non-null  str
 7   positive_ratio  50872 non-null  int64
 8   user_reviews    50872 non-null  int64
 9   price_final     50872 non-null  float64
 10  price_original  50872 non-null  float64
 11  discount        50872 non-null  float64
 12  steam_deck      50872 non-null  bool
 13  description     50872 non-null  str
 14  tags            50872 non-null  object
dtypes: bool(4), float64(3), int64(3), object(1), str(4)
memory usage: 4.5+ MB

In [6]:
df_games_meta = df_games_meta[['app_id', 'title', 'description', 'tags', 'rating']].copy()
df_games_meta.head()

,app_id,title,description,tags,rating
0,13500,Prince of Persia: Warrior Within™,Enter the dark underworld of Prince of Persia ...,"[Action, Adventure, Parkour, Third Person, Gre...",Very Positive
1,22364,BRINK: Agents of Change,,[Action],Positive
2,113020,Monaco: What's Yours Is Mine,Monaco: What's Yours Is Mine is a single playe...,"[Co-op, Stealth, Indie, Heist, Local Co-Op, St...",Very Positive
3,226560,Escape Dead Island,Escape Dead Island is a Survival-Mystery adven...,"[Zombies, Adventure, Survival, Action, Third P...",Mixed
4,249050,Dungeon of the ENDLESS™,Dungeon of the Endless is a Rogue-Like Dungeon...,"[Roguelike, Strategy, Tower Defense, Pixel Gra...",Very Positive

# **4. DATA PREPROCESSING**

### a. Menghapus baris yang memiliki data kosong pada title/deskripsi/tags

In [7]:
# Menghapus baris dengan title, description, atau tags yang kosong
df_games_meta = df_games_meta.fillna('')

df_games_meta = df_games_meta[
    (df_games_meta['title'].astype(str).str.strip() != '') &
    (df_games_meta['description'].astype(str).str.strip() != '') &
    (df_games_meta['tags'].astype(str).str.strip() != '')
].reset_index(drop=True)

display(df_games_meta.head())
print(f"Rows after dropping empty title/description/tags: {df_games_meta.shape[0]}")

,app_id,title,description,tags,rating
0,13500,Prince of Persia: Warrior Within™,Enter the dark underworld of Prince of Persia ...,"[Action, Adventure, Parkour, Third Person, Gre...",Very Positive
1,113020,Monaco: What's Yours Is Mine,Monaco: What's Yours Is Mine is a single playe...,"[Co-op, Stealth, Indie, Heist, Local Co-Op, St...",Very Positive
2,226560,Escape Dead Island,Escape Dead Island is a Survival-Mystery adven...,"[Zombies, Adventure, Survival, Action, Third P...",Mixed
3,249050,Dungeon of the ENDLESS™,Dungeon of the Endless is a Rogue-Like Dungeon...,"[Roguelike, Strategy, Tower Defense, Pixel Gra...",Very Positive
4,250180,METAL SLUG 3,"“METAL SLUG 3”, the masterpiece in SNK’s emble...","[Arcade, Classic, Action, Co-op, Side Scroller...",Very Positive

Rows after dropping empty title/description/tags: 40499

### b. Fungsi-fungsi Preprocessing

In [8]:
def cleaningText(text):
    text = re.sub(r'http\S+', '', text)  # Remove URLs
    text = re.sub(r'@\w+', '', text)  # Remove mentions
    text = re.sub(r'#\w+', '', text)  # Remove hashtags
    text = re.sub(r'\d+', '', text)  # Remove numbers
    text = re.sub(r'[^\w\s]', '', text)  # Remove non-alphanumeric characters

    text = text.translate(str.maketrans('', '', string.punctuation))  # Remove punctuation
    text = text.replace('\n', ' ')  # Remove newlines
    text = text.strip(' ') # Remove leading and trailing whitespace
    return text

def caseFolding(text):
    text = text.lower()
    return text

def tokenizingText(text):
    text = word_tokenize(text)
    return text

def filteringText(text):
    listStopwords = set(stopwords.words('english'))

    filtered_text = []
    for txt in text:
        if txt not in listStopwords:
            filtered_text.append(txt)

    text = filtered_text
    return text

def stemmingText(tokens):
    stemmer = PorterStemmer()
    return [stemmer.stem(token) for token in tokens]

def lemmatizingText(tokens):
    lemmatizer = WordNetLemmatizer()
    return [lemmatizer.lemmatize(token) for token in tokens]
def toSentence(list_words):
    sentence = ' '.join(word for word in list_words)
    return sentence

### c. Membersihkan Kolom Description

In [9]:
df_games_meta_cleaned = df_games_meta.copy()
df_games_meta_cleaned['desc_clean'] = df_games_meta_cleaned['description'].apply(cleaningText)
df_games_meta_cleaned['desc_caseFolded'] = df_games_meta_cleaned['desc_clean'].apply(caseFolding)
df_games_meta_cleaned['desc_tokenized'] = df_games_meta_cleaned['desc_caseFolded'].apply(tokenizingText)
df_games_meta_cleaned['desc_stopword'] = df_games_meta_cleaned['desc_tokenized'].apply(filteringText)
df_games_meta_cleaned['desc_stemmed'] = df_games_meta_cleaned['desc_stopword'].apply(stemmingText)
df_games_meta_cleaned['desc_lemmatized'] = df_games_meta_cleaned['desc_stopword'].apply(lemmatizingText)
df_games_meta_cleaned['desc_sentence'] = df_games_meta_cleaned['desc_lemmatized'].apply(toSentence)
display(df_games_meta_cleaned.head())

,app_id,title,description,tags,rating,desc_clean,desc_caseFolded,desc_tokenized,desc_stopword,desc_stemmed,desc_lemmatized,desc_sentence
0,13500,Prince of Persia: Warrior Within™,Enter the dark underworld of Prince of Persia ...,"[Action, Adventure, Parkour, Third Person, Gre...",Very Positive,Enter the dark underworld of Prince of Persia ...,enter the dark underworld of prince of persia ...,"[enter, the, dark, underworld, of, prince, of,...","[enter, dark, underworld, prince, persia, warr...","[enter, dark, underworld, princ, persia, warri...","[enter, dark, underworld, prince, persia, warr...",enter dark underworld prince persia warrior wi...
1,113020,Monaco: What's Yours Is Mine,Monaco: What's Yours Is Mine is a single playe...,"[Co-op, Stealth, Indie, Heist, Local Co-Op, St...",Very Positive,Monaco Whats Yours Is Mine is a single player ...,monaco whats yours is mine is a single player ...,"[monaco, whats, yours, is, mine, is, a, single...","[monaco, whats, mine, single, player, coop, he...","[monaco, what, mine, singl, player, coop, heis...","[monaco, whats, mine, single, player, coop, he...",monaco whats mine single player coop heist gam...
2,226560,Escape Dead Island,Escape Dead Island is a Survival-Mystery adven...,"[Zombies, Adventure, Survival, Action, Third P...",Mixed,Escape Dead Island is a SurvivalMystery advent...,escape dead island is a survivalmystery advent...,"[escape, dead, island, is, a, survivalmystery,...","[escape, dead, island, survivalmystery, advent...","[escap, dead, island, survivalmysteri, adventu...","[escape, dead, island, survivalmystery, advent...",escape dead island survivalmystery adventure l...
3,249050,Dungeon of the ENDLESS™,Dungeon of the Endless is a Rogue-Like Dungeon...,"[Roguelike, Strategy, Tower Defense, Pixel Gra...",Very Positive,Dungeon of the Endless is a RogueLike DungeonD...,dungeon of the endless is a roguelike dungeond...,"[dungeon, of, the, endless, is, a, roguelike, ...","[dungeon, endless, roguelike, dungeondefense, ...","[dungeon, endless, roguelik, dungeondefens, ga...","[dungeon, endless, roguelike, dungeondefense, ...",dungeon endless roguelike dungeondefense game ...
4,250180,METAL SLUG 3,"“METAL SLUG 3”, the masterpiece in SNK’s emble...","[Arcade, Classic, Action, Co-op, Side Scroller...",Very Positive,METAL SLUG the masterpiece in SNKs emblematic...,metal slug the masterpiece in snks emblematic...,"[metal, slug, the, masterpiece, in, snks, embl...","[metal, slug, masterpiece, snks, emblematic, r...","[metal, slug, masterpiec, snk, emblemat, run, ...","[metal, slug, masterpiece, snks, emblematic, r...",metal slug masterpiece snks emblematic run gun...

In [10]:
drop_columns = ['desc_clean', 'desc_caseFolded', 'desc_tokenized', 'desc_stopword', 'desc_stemmed', 'desc_lemmatized']
df_games_meta_cleaned = df_games_meta_cleaned.drop(columns=drop_columns, errors='ignore')
display(df_games_meta_cleaned.head())

,app_id,title,description,tags,rating,desc_sentence
0,13500,Prince of Persia: Warrior Within™,Enter the dark underworld of Prince of Persia ...,"[Action, Adventure, Parkour, Third Person, Gre...",Very Positive,enter dark underworld prince persia warrior wi...
1,113020,Monaco: What's Yours Is Mine,Monaco: What's Yours Is Mine is a single playe...,"[Co-op, Stealth, Indie, Heist, Local Co-Op, St...",Very Positive,monaco whats mine single player coop heist gam...
2,226560,Escape Dead Island,Escape Dead Island is a Survival-Mystery adven...,"[Zombies, Adventure, Survival, Action, Third P...",Mixed,escape dead island survivalmystery adventure l...
3,249050,Dungeon of the ENDLESS™,Dungeon of the Endless is a Rogue-Like Dungeon...,"[Roguelike, Strategy, Tower Defense, Pixel Gra...",Very Positive,dungeon endless roguelike dungeondefense game ...
4,250180,METAL SLUG 3,"“METAL SLUG 3”, the masterpiece in SNK’s emble...","[Arcade, Classic, Action, Co-op, Side Scroller...",Very Positive,metal slug masterpiece snks emblematic run gun...

### d. Membersihkan Kolom Tags

In [11]:
# bersihkan tags dari spesial karakter
df_games_meta_cleaned['tags_clean'] = df_games_meta_cleaned['tags'].astype(str).apply(cleaningText)
df_games_meta_cleaned

,app_id,title,description,tags,rating,desc_sentence,tags_clean
0,13500,Prince of Persia: Warrior Within™,Enter the dark underworld of Prince of Persia ...,"[Action, Adventure, Parkour, Third Person, Gre...",Very Positive,enter dark underworld prince persia warrior wi...,Action Adventure Parkour Third Person Great So...
1,113020,Monaco: What's Yours Is Mine,Monaco: What's Yours Is Mine is a single playe...,"[Co-op, Stealth, Indie, Heist, Local Co-Op, St...",Very Positive,monaco whats mine single player coop heist gam...,Coop Stealth Indie Heist Local CoOp Strategy O...
2,226560,Escape Dead Island,Escape Dead Island is a Survival-Mystery adven...,"[Zombies, Adventure, Survival, Action, Third P...",Mixed,escape dead island survivalmystery adventure l...,Zombies Adventure Survival Action Third Person...
3,249050,Dungeon of the ENDLESS™,Dungeon of the Endless is a Rogue-Like Dungeon...,"[Roguelike, Strategy, Tower Defense, Pixel Gra...",Very Positive,dungeon endless roguelike dungeondefense game ...,Roguelike Strategy Tower Defense Pixel Graphic...
4,250180,METAL SLUG 3,"“METAL SLUG 3”, the masterpiece in SNK’s emble...","[Arcade, Classic, Action, Co-op, Side Scroller...",Very Positive,metal slug masterpiece snks emblematic run gun...,Arcade Classic Action Coop Side Scroller Retro...
...,...,...,...,...,...,...,...
40494,2515240,Welcome to Kowloon,"This is an indie horror from the first person,...","[Horror, Atmospheric, Psychological Horror, Ad...",Mostly Positive,indie horror first person find area called kow...,Horror Atmospheric Psychological Horror Advent...
40495,2455060,Taboo Trial,"In the rogue action game ""Taboo Trial"", you wi...","[RPG, Indie, Nudity, Action Roguelike, Female ...",Very Positive,rogue action game taboo trial play young femal...,RPG Indie Nudity Action Roguelike Female Prota...
40496,1138640,Hometopia,"Build better, together 🏡 Hometopia is a seriou...","[Early Access, Life Sim, City Builder, Immersi...",Mixed,build better together hometopia seriously sati...,Early Access Life Sim City Builder Immersive S...
40497,1687000,Fading Afternoon,Seiji Maruyama is a middle-aged yakuza recentl...,"[Side Scroller, Beat 'em up, Sandbox, Martial ...",Mostly Positive,seiji maruyama middleaged yakuza recently rele...,Side Scroller Beat em up Sandbox Martial Arts ...
40498,2272250,Forgive Me Father 2,Embark on a journey into the darkest nightmare...,"[Early Access, FPS, Action, Retro, First-Perso...",Very Positive,embark journey darkest nightmare restore sanit...,Early Access FPS Action Retro FirstPerson Love...

# **5. Export Data**

In [12]:
import os

os.makedirs('../data/processed', exist_ok=True)
final_df = df_games_meta_cleaned.copy()
final_df.to_csv('../data/processed/clean_data_games.csv', index=False)
print("Data bersih telah tersimpan.")

Data bersih telah tersimpan.